# run using this command
# docker-compose -f docker-compose.yml -f docker-compose.nonovnc.yml up -d
version: "3.5"
services:
  gui:
    entrypoint: ["echo", "Service novnc disabled"]
  abb-planner:
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=1
